    ##############################
    ##############################
    # This file is automatically generated by the Strimzi Cluster Operator
    # Any changes to this file will be ignored and overwritten!
    ##############################
    ##############################

    FROM quay.io/strimzi/kafka:0.40.0-kafka-3.7.0

    USER root:root

    ##########
    # Connector plugin debezium-pg-connector
    ##########
    RUN 'mkdir' '-p' '/opt/kafka/plugins/debezium-pg-connector/25c63200' \
          && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/debezium-pg-connector/25c63200.zip' 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.1.Final/debezium-connector-postgres-2.6.1.Final-plugin.zip' \
          && 'unzip' '/opt/kafka/plugins/debezium-pg-connector/25c63200.zip' '-d' '/opt/kafka/plugins/debezium-pg-connector/25c63200' \
          && 'find' '/opt/kafka/plugins/debezium-pg-connector/25c63200' '-type' 'l' | 'xargs' 'rm' '-f' \
          && 'rm' '-vf' '/opt/kafka/plugins/debezium-pg-connector/25c63200.zip'

    ##########
    # Connector plugin debezium-jdbc-connector
    ##########
    RUN 'mkdir' '-p' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006' \
          && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006.zip' 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-jdbc/2.6.1.Final/debezium-connector-jdbc-2.6.1.Final-plugin.zip' \
          && 'unzip' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006.zip' '-d' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006' \
          && 'find' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006' '-type' 'l' | 'xargs' 'rm' '-f' \
          && 'rm' '-vf' '/opt/kafka/plugins/debezium-jdbc-connector/dad3d006.zip'

    USER 1001